version: '2'
services:
    db:
        restart: always
    static:
        restart: always
        ports:
            - "80:80"
            - "443:443"
    web:
        command: gunicorn --workers=4 --bind=0.0.0.0:8000 practica.wsgi 
        restart: always
        environment:
            DJANGO_SETTINGS_MODULE: practica.settings.production

    cache:
        restart: always
