version: '2'
services:
    cache:
        image: redis
    static:
        build: ./nginx
        volumes:
            - data:/var/nginx
        links:
            - web:gunicorn
        ports: 
            - "80:80"
    db:
        build: 
            context: .
            dockerfile: postgres_ru_Dockerfile
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
            PGDATA: "/var/lib/postgresql/data/pgdata"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - cache
            - db
        links:
            - cache:redis
        volumes:
            - data:/data
        environment:
            DJANGO_SECRET_KEY:
            PRACTICA_ROBOKASSA_PASSWORD1:
            PRACTICA_ROBOKASSA_PASSWORD2:
            PRACTICA_GOOGLE_ANALYTICS_ID:
            PRACTICA_YANDEX_METRIKA_ID:
            PRACTICA_EMAIL:
            PRACTICA_EMAIL_PASSWORD:
            DJANGO_SETTINGS_MODULE: practica.settings.testing
volumes:
    data:
        external:
            name: practica
