version: "3.7"

services:

    cache:
      image: redis
    static:
      image: nginx
      volumes:
          - ./nginx/${ENV_TYPE}.conf:/etc/nginx/conf.d/default.conf
          - data:/var/nginx
          - ./__local__/certbot/conf:/etc/letsencrypt
          - ./__local__/certbot/www:/var/www/certbot
      env_file:
        - .env
      links:
            - web:gunicorn
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
      image: certbot/certbot
      volumes:
          - ./__local__/certbot/conf:/etc/letsencrypt
          - ./__local__/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    db:
      build:
        context: .
        dockerfile: postgres_ru_Dockerfile
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER:
        POSTGRES_PASSWORD:
        POSTGRES_DB:
        PGDATA: "/var/lib/postgresql/data/pgdata"
    web:
      build: .
      depends_on:
        - cache
        - db
      links:
        - cache:redis
      volumes:
        - data:/data
      env_file:
        - .env
volumes:
  data:
      external:
            name: practica
