version: "3.5"

services:
    traefik:
        restart: always
        image: "traefik:v2.2"
        command:
        - "--log.level=DEBUG"
        - "--api.insecure=false"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        - "--certificatesresolvers.myresolver.acme.email=ap@ucoders.dev"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
        - "8000:443"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "letsencrypt:/letsencrypt"

    cache:
      image: redis
    db:
      build:
        context: .
        dockerfile: postgres_ru_Dockerfile
      volumes:
        - data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER:
        POSTGRES_PASSWORD:
        POSTGRES_DB:
        PGDATA: "/var/lib/postgresql/data/pgdata"
    web:
      build: .
      depends_on:
        - cache
        - db
      links:
        - cache:redis
      volumes:
        - data:/data
      environment:
        DJANGO_SECRET_KEY:
        PRACTICA_ROBOKASSA_PASSWORD1:
        PRACTICA_ROBOKASSA_PASSWORD2:
        PRACTICA_GOOGLE_ANALYTICS_ID:
        PRACTICA_YANDEX_METRIKA_ID:
        PRACTICA_EMAIL:
        PRACTICA_EMAIL_PASSWORD:
        DJANGO_SETTINGS_MODULE: practica.settings.testing
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`practica.ru`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.static.tls.certresolver=myresolver"
volumes:
  data:
  letsencrypt:
